### ISSUE TITLE
Interest

### ISSUE THREAD

**Issue by PhoneDroid** [DerM4209/DIY_Inkjet_Printer#1]
I wrote this message on Hackaday but I can't see my 
own messages and I'm not sure they were even sent.

I was wondering if you had any interest in making
this repository into a proper project hub, with
updated code, documentation, ..

If so, I'd love to contribute said work,
if not, I'll be making a mirror of it.

As an important side note, you haven't
specified any licenses for your code / parts.

Check out https://choosealicense.com/licenses/
for licenses in general, I would recommend:

| Content | File in repo | License |
|:-------:|:------------:|:-------:|
| Software | `LICENSE` | [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/)
| Hardware | `LICENSE_HARDWARE` | [OHL v2 Strongly Reciprocal](https://choosealicense.com/licenses/cern-ohl-s-2.0/)
| Images | `LICENSE_IMAGES` | [CC-BY-SA 4.0](https://choosealicense.com/licenses/cc-by-sa-4.0/)

I could also add them when contributing.

If you have any questions, let me know!

**Comment by DerM4209** [comment]
Hi,
I saw your message on Hackaday.

I would really like to add the missing bits to the project like the license and updated code, but I have not much experience using Github - just used it for sharing some code with the link to the repository.

I added the AGPLv3 license to the project.

**Comment by PhoneDroid** [comment]
@DerM4209 Well I can do that work for you,
also if you have any questions regarding
GitHub, let me know!

**Comment by PhoneDroid** [comment]
@DerM4209 I opened a DRAFT pull request.

#2 

I will notify you once I'm done with it.

Link to my fork / where I'm working on it:


https://github.com/PhoneDroid/Contribute-DIY_Inkjet_Printer

**Comment by DerM4209** [comment]
Ok,
thank you very much :)

**Comment by PhoneDroid** [comment]
@DerM4209 Little update.

- Imported images from hackaday ( though currently only numbered, will be named / categorized later )
- Wrote a little documentation for GCode
- Added a video overview ( https://github.com/PhoneDroid/Contribute-DIY_Inkjet_Printer/blob/Documentation/Documentation/Videos.md )
- Made some simplified circuit diagrams
  - No labels yet
  - Meant for showcasing the structure, not layout

**Comment by PhoneDroid** [comment]
Btw, I would recommend creating an organization for yout DIY printer projects.

The name `DIYPrinters` is still available for example.

If you need help with it, let me know!

**Comment by DerM4209** [comment]
@PhoneDroid 
Thank you very much for the great work you are doing with the documentation.

How can I organize the projects? Will I have to create a new repository for it?

**Comment by PhoneDroid** [comment]
@DerM4209 No, in the repository settings,
at the very bottom there is a button called
`transfer`, after you have created your
organization, you can transfer them to it.

**Comment by PhoneDroid** [comment]
<br>

@DerM4209 Btw, if you wouldn't mind, do you 
have a more direct communication channel?

( Matrix , Session , Discord , .. )

<br>

## Detailed Instructions ( Organization )

<br>

### Creation

1. Open the dropdown menu of you avatar ( upper right corner )

2. Click the 3rd option `Your organizations`

3. Click `New Organization`

4. Fill out the information, be sure to properly capitalize the organization name ( `DIYPrinters` for example )

<br>

### Transfer

1. Below the repository title, click the `Settings` tab

2. Scroll to the bottom and click the 2nd red option ( `Transfer` )

3. Under `Select one of my organizations` choose your newly created one

<br>

**Comment by DerM4209** [comment]
Hi John,
I created the organization DIY-Inkjet-Printers and transferred the repository to it.

You can chat with me on Discord.

**Comment by PhoneDroid** [comment]
Do you have a related server / what's your Discord handle?

**Comment by DerM4209** [comment]
I have no server, but here is my ID:
DerM4209#9229

**Comment by Maniues** [comment]
@DerM4209 @PhoneDroid 
Hey, I found this project and it seems very interesting. Are there any updates on uploading all the files and licenses to GitHub?

**Comment by PhoneDroid** [comment]
Oh woops , I kinda forgot about it~
I'll have a look through it today

**Comment by PhoneDroid** [comment]
@Maniues Btw #2 is the PR I was working 
on , in case you didn't see it.
